GET http://localhost:3000/task

###
GET http://localhost:3000/task/26321a88-3f6c-4cc7-a560-a7f7dbe43b56

###
POST http://localhost:3000/task
Content-Type: application/json

{
  "title": "Tarefa 1",
  "description": "To do"
}

### 
PUT  http://localhost:3000/task/26321a88-3f6c-4cc7-a560-a7f7dbe43b56
Content-Type: application/json

{
  "title": "Tarefa 1",
  "description": "Fazer"
}

###
DELETE  http://localhost:3000/task/26321a88-3f6c-4cc7-a560-a7f7dbe43b56